### ISSUE TITLE
Constant.tabBarHeight 这个是什么？？

### ISSUE THREAD

**Issue by daimengxiaozhi** [tonySwiftDev/UITabbar-fixIOS12.1Bug#1]

**Comment by daimengxiaozhi** [comment]
应该是48吧 。
 UIDevice().userInterfaceIdiom == .phone && UIScreen.main.nativeBounds.height == 2436  后面的条件有什么作用？？

**Comment by tonySwiftDev** [comment]
1.你好，请重新下文件。这个变量值Constant.tabBarHeight已经去掉了。
2.UIScreen.main.nativeBounds.height == 2436这句话是为了判断iphoneX系统的机型。目前也做了一些更改。更新下文件就行。
3.iphoneX系统的机型 默认tabbarHeight设置为48，但是大部分做了适配的，没有使用48这个值。
更新后的文件也提供kIPhoneXSeriesTabbarButtonHeight，你根据你实际项目进行修改。

**Comment by tonySwiftDev** [comment]
> 应该是48吧 。
> UIDevice().userInterfaceIdiom == .phone && UIScreen.main.nativeBounds.height == 2436 后面的条件有什么作用？？

请更新下文件，更改kIPhoneXSeriesTabbarButtonHeight的值。

**Comment by daimengxiaozhi** [comment]
let kIPhoneXSeriesTabbarButtonHeight: CGFloat = 88.0  怎么变成88了
